---
- name: Configure Kubelet service 
  template: src=kubelet_config.j2 dest=/etc/kubernetes/kubelet mode=0755

- name: Enable and Restart flannel
  service: name=flanneld enabled=yes state=restarted

- name: Enable and Restart docker
  service: name=docker enabled=yes state=restarted

- name: Enable and restart kube-proxy
  service: name=kube-proxy  enabled=yes state=restarted

- name: Enable and Restart kubelet
  service: name=kubelet enabled=yes state=restarted

