---
- name: Containers | Installing dockers
  action: yum pkg={{ item }} state=installed
  with_items:
    - docker
    - docker-logrotate

- name: Start docker service
  service: name=docker state=started

- name: Create docker group
  shell: groupadd docker
  ignore_errors: yes

- name: Add your vagrant user to the docker group
  shell: gpasswd -a vagrant docker

- name: Restart docker service
  service: name=docker state=restarted

- name: Cluster Orchestrator | Installing kubernetes
  action: yum pkg={{ item }} state=installed
  with_items:
    - kubernetes
    - etcd
    - flannel

- name: Configure kubernetes
  template: src=kubernetes_config.j2 dest=/etc/kubernetes/config mode=0664

- name: Configure ETCD Service
  template: src=etcd_config.j2 dest=/etc/etcd/etcd.conf mode=0664

- name: Configure Flannel Service
  template: src=flannel_config.j2 dest=/etc/sysconfig/flanneld mode=0664

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].inventory_hostname }} {{ hostvars[item].cluster_host }} {{ hostvars[item].cluster_host }}.com"
    state: present
  with_items: "{{ groups.all }}"

- name: Http | Intalling Http client library 
  pip:
    name: httplib2
